syntax = "proto3";

package mailbox;
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";

enum ErrorCode {
    OK = 0;
    MISSING_REQUIRED_FIELD = 1;
    INVALID_ADDRESS = 2;
    INVALID_PAYLOAD = 3;
    INTERNAL_ERROR = 4;
}

//enum ResponseType
//{
//}


// message MailboxRequest {
 //   string request_id = 1;
 //   string source     = 2;
 //   MessageType = 3; 
 //   bool success = 4;//optional
 //   string destination = 3;//option
 //   // this will creata an interface for other later modules to define its own request and response type
  //  google.protobuf.Any payload = 4;
//}
//enum MessageType {
  //  VALIDATE = 0;
  //  REQUEST = 1;
  //  RESPONSE = 2;
//}

message MailboxRequest {
    string request_id = 1;
    string source     = 2;
    string destination = 3;//option
    // this will creata an interface for other later modules to define its own request and response type
    google.protobuf.Any payload = 4;
 //   MessageType message_type = 5;
}

//message MailboxResponse {
   
 //   MailboxRequest request = 1
 //   bool success = 2
 //   ResponseType type = 3

//}

// return empty here because gRPC force to return something when sending.
// so the Response instead of directly sent back, I will send an Empty message
// the real response will be sent by another SendMessage() call from the other side
service MailboxService {
    rpc SendMessage(MailboxRequest) returns (google.protobuf.Empty);
}

// enum NodeType {
//     NODE_UNKNOWN = 0;
//     DU           = 1;
//     RU           = 2;
//     ANTENNA      = 3;
// }

// message NodeInfo {
//     string   node_id   = 1;
//     NodeType node_type = 2;
// }

// message Metadata {
//     string timestamp      = 1;
//     string correlation_id = 2;
//     string version        = 3;
// }

// enum MessageType {
//     MSG_UNKNOWN = 0;
//     CONFIG      = 1;
//     START       = 2;
//     STOP        = 3;
//     STATUS      = 4;
//     HELLO       = 5;
// }

// enum ErrorCode {
//     OK                     = 0;
//     INVALID_FORMAT         = 1;
//     MISSING_REQUIRED_FIELD = 2;
//     INVALID_METADATA       = 3;
//     INVALID_MESSAGE_TYPE   = 4;
//     UNSUPPORTED_MESSAGE    = 5;
//     HANDLER_NOT_FOUND      = 6;
//     INTERNAL_ERROR         = 7;
// }

// // message RURequest {
// }
// //     // RU-specific fields
// // }

// // message DURequest {
// //     // DU-specific fields
// // }
// message MailboxResponse {
//     bool      success    = 1;
//     ErrorCode error_code = 2;
//     string    message    = 3;
//     string    request_id = 4;
// }
